name       : grisbi
version    : 1.0.0
release    : 1
source     :
    - http://downloads.sourceforge.net/grisbi/grisbi-1.0.0.tar.bz2 : 8a23d26777666814d918702ad9207bac433abd3ac71568d53f7c485670f92c55
license    : GPL-2.0
summary    : A basic finance program to manage your accounts
description: |
    - A basic finance program to manage your accounts
builddeps  : 
    - pkgconfig(gtk+-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
