name       : grisbi
version    : 1.0.1
release    : 2
source     :
    - https://svwh.dl.sourceforge.net/project/grisbi/grisbi%20stable/1.0.x/grisbi-1.0.1.tar.bz2 : ed52fa6b3a7be3b0c588702e6d85afc8f6a699142eba0ae82eafcd360aee0414
license    : GPL-2.0
component  : office
summary    : Personal finance manager
description: |
    Grisbi is a personal accounting application capable of managing multiple accounts, currencies and users.Grisbi is a personal accounting application capable of managing multiple accounts, currencies and users.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libofx)
    - gettext
    - grep
setup      : |
    %configure --disable-frenchdoc
build      : |
    %make
install    : |
    %make_install
