name       : grisbi
version    : 1.0.2
release    : 4
source     :
    - https://nchc.dl.sourceforge.net/project/grisbi/grisbi%20stable/1.0.x/grisbi-1.0.2.tar.bz2 : f5ab794ab1b04141402ae50cdc2d37cfaf245ace422812b3193f9548605061d4
license    : GPL-2.0
component  : office.finance
summary    : Personal finance manager
description: |
    Grisbi is a personal accounting application capable of managing multiple accounts, currencies and users.Grisbi is a personal accounting application capable of managing multiple accounts, currencies and users.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libofx)
setup      : |
    %configure --disable-frenchdoc
build      : |
    %make
install    : |
    %make_install
